# Copyright (c) 2020. TIBCO Software Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

# set certified JRE image version for the
# JasperReports Server command line tools

# for JasperReports Server 7.5
# ARG JAVA_BASE_IMAGE=amazoncorretto:11

FROM tomcat:9.0.27-jdk11-openjdk

ENV POSTGRES_JDBC_DRIVER_VERSION ${POSTGRES_JDBC_DRIVER_VERSION:-42.2.5}
ENV JASPERREPORTS_SERVER_VERSION ${JASPERREPORTS_SERVER_VERSION:-7.5.1}
ENV EXPLODED_INSTALLER_DIRECTORY ${EXPLODED_INSTALLER_DIRECTORY:-resources/jasperreports-server-pro-$JASPERREPORTS_SERVER_VERSION-bin}

# This Dockerfile requires an exploded JasperReports Server WAR file installer file 
# in the resources directory below the Dockerfile.

# COPY the buildomatic, command line scripts and supporting resources
# from the JasperReports Server WAR file installer into the image

RUN mkdir -p /usr/src/jasperreports-server

# Ant
COPY ${EXPLODED_INSTALLER_DIRECTORY}/apache-ant /usr/src/jasperreports-server/apache-ant/

# js-ant script, Ant XMLs and supporting resources in bin
COPY ${EXPLODED_INSTALLER_DIRECTORY}/buildomatic/js-ant /usr/src/jasperreports-server/buildomatic/
COPY ${EXPLODED_INSTALLER_DIRECTORY}/buildomatic/js-*.sh /usr/src/jasperreports-server/buildomatic/
COPY ${EXPLODED_INSTALLER_DIRECTORY}/buildomatic/*.xml /usr/src/jasperreports-server/buildomatic/
COPY ${EXPLODED_INSTALLER_DIRECTORY}/buildomatic/bin/*.sh /usr/src/jasperreports-server/buildomatic/bin/
COPY ${EXPLODED_INSTALLER_DIRECTORY}/buildomatic/bin/*.xml /usr/src/jasperreports-server/buildomatic/bin/
COPY ${EXPLODED_INSTALLER_DIRECTORY}/buildomatic/bin/*.help /usr/src/jasperreports-server/buildomatic/bin/
COPY ${EXPLODED_INSTALLER_DIRECTORY}/buildomatic/bin/app-server /usr/src/jasperreports-server/buildomatic/bin/app-server/
COPY ${EXPLODED_INSTALLER_DIRECTORY}/buildomatic/bin/groovy /usr/src/jasperreports-server/buildomatic/bin/groovy/

# supporting resources
COPY ${EXPLODED_INSTALLER_DIRECTORY}/buildomatic/jdbc-dep /usr/src/jasperreports-server/buildomatic/bin/jdbc-dep/
COPY ${EXPLODED_INSTALLER_DIRECTORY}/buildomatic/install_resources /usr/src/jasperreports-server/buildomatic/install_resources/
COPY ${EXPLODED_INSTALLER_DIRECTORY}/buildomatic/conf_source /usr/src/jasperreports-server/buildomatic/conf_source/
COPY ${EXPLODED_INSTALLER_DIRECTORY}/buildomatic/target /usr/src/jasperreports-server/buildomatic/target/

COPY scripts /

RUN echo "apt-get" && \
    echo "nameserver 8.8.8.8" | tee /etc/resolv.conf > /dev/null && \
    chmod +x /*.sh && \
    /installPackagesForJasperserver-pro-cmdline.sh && \
	echo "finished installing packages" && \
	cp -R /buildomatic /usr/src/jasperreports-server/buildomatic && \
	rm /installPackagesForJasperserver*.sh && rm -rf /buildomatic && \
	chmod +x /usr/src/jasperreports-server/buildomatic/js-* && \
	chmod +x /usr/src/jasperreports-server/buildomatic/bin/*.sh && \
	chmod +x /usr/src/jasperreports-server/apache-ant/bin/* && \
    java -version && \
    wget "https://jdbc.postgresql.org/download/postgresql-${POSTGRES_JDBC_DRIVER_VERSION}.jar"  \
        -P /usr/src/jasperreports-server/buildomatic/conf_source/db/postgresql/jdbc --no-verbose

# permanently copy license ERAMON - verify copy & run Befehle
COPY license/jasperserver.license /usr/src/jasperreports-server/jasperserver.license
# copy cipher class
COPY security/java/MyCipher.jar /usr/local/tomcat/webapps/jasperserver-pro/WEB-INF/lib/MyCipher.jar
# copy auth-config
COPY security/config/applicationContext-externalAuth-preauth.xml /usr/local/tomcat/webapps/jasperserver-pro/WEB-INF/applicationContext-externalAuth-preauth.xml
# copy formatting definition for FormatValueByUnit
COPY formatting/applicationContext-el-operators.xml /usr/local/tomcat/webapps/jasperserver-pro/WEB-INF/applicationContext-el-operators.xml
# copy groovy function for FormatValueByUnit
COPY formatting/BaseGroovyColumn.groovy /usr/local/tomcat/webapps/jasperserver-pro/WEB-INF/groovy/groovy_column/BaseGroovyColumn.groovy
# copy MySQL driver
COPY driver/mariadb-java-client-1.6.3.jar /usr/src/jasperreports-server/buildomatic/conf_source/db/mysql/jdbc/mariadb-java-client-1.6.3.jar
RUN chmod +x /usr/src/jasperreports-server/buildomatic/conf_source/db/mysql/jdbc/mariadb-java-client-1.6.3.jar && \
	chmod +x /usr/local/tomcat/webapps/jasperserver-pro/WEB-INF/applicationContext-externalAuth-preauth.xml && \
	chmod +x /usr/local/tomcat/webapps/jasperserver-pro/WEB-INF/applicationContext-el-operators.xml && \
	chmod +x /usr/local/tomcat/webapps/jasperserver-pro/WEB-INF/groovy/groovy_column/BaseGroovyColumn.groovy && \
	chmod +x /usr/local/tomcat/webapps/jasperserver-pro/WEB-INF/lib/MyCipher.jar && \
	chmod +x /usr/src/jasperreports-server/jasperserver.license

ENTRYPOINT ["/entrypoint-cmdline.sh"]

# Default action executed by entrypoint script.
CMD ["init"]
