# Copyright (c) 2019. TIBCO Software Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

# docker-compose.yml example for JasperReports Server

version: '2'

services:
  jasperserver-pro:
    image: "jasperserver-pro:${JASPERREPORTS_SERVER_VERSION}"
    
    build:
      context: .
      args:
        - "JASPERREPORTS_SERVER_VERSION=${JASPERREPORTS_SERVER_VERSION}"
        - "TOMCAT_BASE_IMAGE=${TOMCAT_BASE_IMAGE}"
    
    # expose port on the host
    ports:
      - 8090:8080
      - 8493:8443
    
    # set depends on js_database Postgresql service
    depends_on:
      - jasperserver_pro_repository
    
    # point to env file with key=value entries 
    env_file: .env-mysql
    
    # setting following values here will override settings from env_file
    environment:
      - DB_HOST=jasperserver_pro_repository
      # - JRS_LOAD_SAMPLES=true

    volumes:
      # where jasperserver.license file is. Otherwise uses temporary license
      - /C/Users/swood/Documents/License:/usr/local/share/jasperserver-pro/license 
      
      # zip files in alphabetical order exploded into webapps/jasperserver-pro
      #- jrs_customization:/usr/local/share/jasperserver-pro/customization
      
      # zip files in alphabetical order exploded into $CATALINA_HOME
      #- jrs_tomcat_customization:/usr/local/share/jasperserver-pro/tomcat-customization
      
      # SSL .keystore files in this volume loaded into /root.
      # needs KS_PASSWORD environment variable set
      #- ssl_certificate:/usr/local/share/jasperserver-pro/ssl-certificate

      # As of JasperReports Server 7.5, this volume :
      #   - saves .jrsks and .jrsksp files if they are created
      #   - provides access to pre-existing keystore related files
      - /C/Users/swood/Documents/Docker/keystore-container-deployment:/usr/local/share/jasperserver-pro/keystore
      
      # include a new version of a JDBC driver for repository databases supported by 
      # JasperReports Server.
      # valid dbTypes are: postgresql, mysql, sqlserver, oracle, db2
      #- /path/to/JDBC/driver:/usr/src/jasperreports-server/buildomatic/conf_source/db/<dbType>/jdbc
      # set environment property:
      # maven.jdbc.version=<version # of JDBC driver>
      # have a look at buildomatic/conf_source/db/<dbType> for db.properties for a dbType
      - /C/Users/swood/Documents/Docker/mysql:/usr/src/jasperreports-server/buildomatic/conf_source/db/mysql/jdbc 
      
      # for Mac OS you may want to define local path for volume mounts. 
      # Note that defining path for a named volume is not supported 
      # by Compose. For example:
      # - /some-local-path:/usr/local/tomcat/webapps/jasperserver-pro
      # - ~/jasperserver-pro/license:/usr/local/share/jasperserver-pro/license
      # - /tmp/customization:/usr/local/share/jasperserver-pro/customization
      #
      # Under Docker for Windows, volumes have to be under the logged in user's User area
      #  - /C/Users/aUser/Documents/License:/usr/local/share/jasperserver-pro/license 

    mem_limit: 3g
    mem_reservation: 1g
    cpu_shares: 256
  
  jasperserver-pro-cmdline:
    image: "jasperserver-pro-cmdline:${JASPERREPORTS_SERVER_VERSION}"
    
    build:
      context: .
      dockerfile: Dockerfile-cmdline
      args:
        - "JASPERREPORTS_SERVER_VERSION=${JASPERREPORTS_SERVER_VERSION}"
    
    # set depends on js_database Postgresql service
    depends_on:
      - jasperserver_pro_repository
    
    # point to env file with key=value entries 
    env_file: .env-mysql
    
    # setting following values here will override settings from env_file
    environment:
      - DB_HOST=jasperserver_pro_repository
      - JRS_LOAD_SAMPLES=true

    volumes:
      # where jasperserver.license file is. Otherwise uses temporary license
      - /C/Users/swood/Documents/License:/usr/local/share/jasperserver-pro/license 
      
      # zip files in alphabetical order exploded into webapps/jasperserver-pro
      #- jrs_customization:/usr/local/share/jasperserver-pro/customization
      
      # zip files in alphabetical order exploded into $CATALINA_HOME
      #- jrs_tomcat_customization:/usr/local/share/jasperserver-pro/tomcat-customization
      
      # SSL .keystore files in this volume loaded into /root.
      # needs KS_PASSWORD environment variable set
      #- ssl_certificate:/usr/local/share/jasperserver-pro/ssl-certificate

      # As of JasperReports Server 7.5, this volume :
      #   - saves .jrsks and .jrsksp files if they are created
      #   - provides access to pre-existing keystore related files
      - /C/Users/swood/Documents/Docker/keystore-container-deployment:/usr/local/share/jasperserver-pro/keystore
      
      # default_master_additional.properties file added to default_master.properties
      # see "To install the WAR file using js-install scripts" in JasperReports Server Installation Guide
      #- /C/Users/swood/Documents/Docker/additional:/usr/local/share/jasperserver-pro/deploy-customization
      
      # include a new version of a JDBC driver for repository databases supported by 
      # JasperReports Server.
      # valid dbTypes are: postgresql, mysql, sqlserver, oracle, db2
      #- /path/to/JDBC/driver:/usr/src/jasperreports-server/buildomatic/conf_source/db/<dbType>/jdbc
      # set environment property:
      # maven.jdbc.version=<version # of JDBC driver>
      # have a look at buildomatic/conf_source/db/<dbType> for db.properties for a dbType
      - /C/Users/swood/Documents/Docker/mysql:/usr/src/jasperreports-server/buildomatic/conf_source/db/mysql/jdbc 
      
      # for Mac OS you may want to define local path for volume mounts. 
      # Note that defining path for a named volume is not supported 
      # by Compose. For example:
      # - /some-local-path:/usr/local/tomcat/webapps/jasperserver-pro
      # - ~/jasperserver-pro/license:/usr/local/share/jasperserver-pro/license
      # - /tmp/customization:/usr/local/share/jasperserver-pro/customization
      #
      # Under Docker for Windows, volumes have to be under the logged in user's User area
      #  - /C/Users/aUser/Documents/License:/usr/local/share/jasperserver-pro/license
      
      # for import/export
      - /C/Users/swood/Documents/Docker/jrs-import:/usr/local/share/jasperserver-pro/import

    mem_limit: 3g
    mem_reservation: 1g
    cpu_shares: 256
 
 # repository and sample databases too if configured
  jasperserver_pro_repository:
    image: mariadb:10.4
    env_file: .env-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
  #jrs_license:
  #jrs_customization:
