
ARG JasperReportsServerVersion

ENV JasperReportsServerVersion		${JasperReportsServerVersion:-7.2.0}

FROM jasperserver-pro:${JasperReportsServerVersion}

COPY scripts/entrypoint-aws.sh /entrypoint-aws.sh

RUN apt-get update > /dev/null && \
	apt-get install -y --no-install-recommends apt-utils  > /dev/null && \
	apt-get install -y \
		python3 \
        python3-pip \
        groff \
        less > /dev/null && \
    pip3 install awscli --upgrade && \
    rm -rf /var/lib/apt/lists/* && \
	chmod +x /entrypoint-aws.sh && \
    ls -lsa /

ENTRYPOINT ["/entrypoint-aws.sh"]

# Default action executed by entrypoint script.
CMD ["run"]

