FROM jasperserver-pro:7.2.0

RUN apt-get update > /dev/null && \
	apt-get install -y --no-install-recommends apt-utils  > /dev/null && \
	apt-get install -y \
		python3 \
        python3-pip \
        groff \
        less > /dev/null && \
    pip3 install awscli --upgrade && \
    rm -rf /var/lib/apt/lists/*

COPY scripts/entrypoint-aws.sh /entrypoint-aws.sh
RUN chmod +x /entrypoint-aws.sh && \
    ls -lsa /


ENTRYPOINT ["/entrypoint-aws.sh"]

# Default action executed by entrypoint script.
CMD ["run"]

