#jgroups.application.initial_hosts=infinispan-node0[7800],infinispan-node1[7800]
jgroups.application.main.bind_port=7800

#jgroups.hibernate.metadata.initial_hosts=infinispan-node0[7810],infinispan-node1[7810]
jgroups.hibernate.metadata.bind_port=7810

#jgroups.hibernate.audit.initial_hosts=infinispan-node0[7820],infinispan-node1[7820]
jgroups.hibernate.audit.bind_port=7820

#jgroups.hibernate.audit.initial_hosts=infinispan-node0[7830],infinispan-node1[7830]
jgroups.hibernate.profiling.bind_port=7830

#bind_address=infinispan-node1
#jgroups.mcast_addr=224.0.0.10