{{- if and  .Values.db.env  (not .Values.db.secretName) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: jasperserver-pro-db-secret
  labels:
    {{- include "jrs.labels" . | nindent 4 }}
data:
  DB_HOST:  {{ .Values.db.jrs.dbHost | toString  | b64enc | quote }}
  DB_PORT:  {{ .Values.db.jrs.dbPort | toString | b64enc | quote  }}
  DB_NAME: {{ .Values.db.jrs.dbName | toString | b64enc  | quote }}
  DB_USER_NAME: {{ .Values.db.jrs.dbUserName | toString | b64enc | quote }}
  DB_PASSWORD:  {{ .Values.db.jrs.dbPassword | toString | b64enc | quote }}
  {{- if .Values.db.audit.enabled }}
  AUDIT_DB_HOST: {{ .Values.db.audit.dbHost | toString  | b64enc | quote }}
  AUDIT_DB_PORT:  {{ .Values.db.audit.dbPort  | toString  | b64enc | quote }}
  AUDIT_DB_NAME: {{ .Values.db.audit.dbName | toString  | b64enc | quote }}
  AUDIT_DB_USER_NAME: {{ .Values.db.audit.dbUserName  | toString  | b64enc | quote }}
  AUDIT_DB_PASSWORD: {{ .Values.db.audit.dbPassword  | toString  | b64enc | quote }}
  {{- end }}
  {{- end}}