version: '2'

services:
  
#####################

  jrs-pro-1:
    image: jasperserver-pro:7.2.0
    
    # expose ports for outside world
    # not needed behind proxy
    #ports:
    #  - 8080:8080
    #  - 8443:8443

    env_file: .cluster-env

    # if set these values override settings from env_file
    #environment:

    volumes:
        - /path/to/jasperserver.license/directory:/usr/local/share/jasperserver-pro/license 
        - /path/to/jasperserver-pro/customization/directory:/usr/local/share/jasperserver-pro/customization 
        #- /path/to/.keystore/directory:/usr/local/share/jasperserver-pro/keystore 
        #- /path/to/tomcat/customization/directory:/usr/local/share/jasperserver-pro/tomcat-customization 

    mem_limit: 3g
    mem_reservation: 1g
    cpu_shares: 256

    depends_on:
        - activemq
    # if using Postgres in a container
    #  - js_database

#####################

  jrs-pro-2:
    image: jasperserver-pro:7.2.0
    
    # expose ports for outside world 
    # not needed behind proxy
    #ports:
    #  - 8080:8080
    #  - 8443:8443

    env_file: .cluster-env

    # if set these values override settings from env_file
    #environment:

    volumes:
        - /path/to/jasperserver.license/directory:/usr/local/share/jasperserver-pro/license 
        - /path/to/jasperserver-pro/customization/directory:/usr/local/share/jasperserver-pro/customization 
        #- /path/to/.keystore/directory:/usr/local/share/jasperserver-pro/keystore 
        #- /path/to/tomcat/customization/directory:/usr/local/share/jasperserver-pro/tomcat-customization 

    mem_limit: 3g
    mem_reservation: 1g
    cpu_shares: 256

    depends_on:
        - activemq
    # if using Postgres in a container
    #  - js_database
  
#####################

  haproxy:
    image: haproxy:1.8
    ports:
        - 80:80
        - 9999:9999
    volumes:
        - /path/to/haproxy.cfg/directory:/usr/local/etc/haproxy
    depends_on:
        - jrs-pro-1
        - jrs-pro-2
  
#####################

  activemq:
    # Runs ActiveMQ JMS on port 61616
    image: rmohr/activemq:5.15.9-alpine

  
#####################

# if you are using postgres within Docker
#  js_database:
#    image: postgres:10
#    env_file: .cluster-env
