

# JasperReports Server command line image, saving keystore changes to a secret.
# Leverages base JRS image of same version

ARG JASPERREPORTS_SERVER_VERSION=7.5.0

FROM jasperserver-pro-cmdline:${JASPERREPORTS_SERVER_VERSION}

ENV JASPERREPORTS_SERVER_VERSION        ${JASPERREPORTS_SERVER_VERSION:-7.5.0}

COPY scripts /

# load kubectl
RUN apt-get update > /dev/null && \
    apt-get install -y apt-transport-https curl gnupg jq > /dev/null && \
    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list && \
    apt-get update > /dev/null && \
    apt-get install -y kubectl

ENTRYPOINT ["/entrypoint-cmdline-k8s.sh"]

# Default action executed by entrypoint script.
CMD ["init"]

