# Copyright © 2021-2023. Cloud Software Group, Inc. All Rights Reserved. Confidential & Proprietary..
# This file is subject to the license terms contained
# in the license file that is distributed with this file
version: "3.9"
services:

##### Jasper Report Server Web Application
  jasperserver-webapp:
    image: "${JASPERREPORTS_SERVER_APP_IMAGE_NAME}:${JASPERREPORTS_SERVER_APP_IMAGE_TAG}"
    env_file:
      - .env
    build:
      context: ../../../
      dockerfile: ./jaspersoft-containers/Docker/jrs/Dockerfile
      args:
        - INSTALL_CHROMIUM
        - JASPERREPORTS_SERVER_VERSION
        - TOMCAT_BASE_IMAGE
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      JAVA_OPTS: "-XX:+UseContainerSupport -XX:MinRAMPercentage=33.0 -XX:MaxRAMPercentage=75.0 -Djs.license.directory=/usr/local/share/jasperserver-pro/license --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.lang.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio.channels.spi=ALL-UNNAMED --add-opens java.base/java.nio.channels=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/java.security=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens java.base/java.util.concurrent.locks=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED --add-opens java.base/java.util.regex=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/javax.security.auth.login=ALL-UNNAMED --add-opens java.base/javax.security.auth=ALL-UNNAMED --add-opens java.base/jdk.internal.access.foreign=ALL-UNNAMED --add-opens java.base/sun.net.util=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.rmi/sun.rmi.transport=ALL-UNNAMED --add-opens java.base/sun.util.calendar=ALL-UNNAMED"
    volumes:
      - ./resources/keystore:/usr/local/share/jasperserver-pro/keystore
      - ./resources/license/jaspersoft.jrs.license:/usr/local/share/jasperserver-pro/license/jaspersoft.jrs.license
    mem_limit: 6g
    mem_reservation: 3g
    cpu_shares: 1000
    depends_on:
      - repository

##### JasperReportServer repository, import and export configuration
  jasperserver-buildomatic:
    image: "${JASPERREPORTS_SERVER_BUILDOMATIC_IMAGE_NAME}:${JASPERREPORTS_SERVER_BUILDOMATIC_IMAGE_TAG}"
    env_file:
      - .env
    build:
      context: ../../../
      dockerfile: ./jaspersoft-containers/Docker/jrs/Dockerfile.buildomatic
      args:
        - JASPERREPORTS_SERVER_VERSION
        - JDK_BASE_IMAGE
    command: ${JS_INSTALL_TARGETS}
    volumes:
      - ./resources/keystore:/usr/local/share/jasperserver-pro/keystore
    depends_on:
      - repository

 ##### JasperReportServer Repository
  repository:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    name: jrs-repository-vol